default_context:
  project_name: 'untimed'
  project_slug: 'untimed'
  domain_main: 'untimed.com'
  domain_staging: 'stag.untimed.com'
  docker_swarm_stack_name_main: 'untimed-com'
  docker_swarm_stack_name_staging: 'stag-untimed-com'
  secret_key: '9da3fb621c14d31e31b3480678b4987dcb21bc33ae31db3551a85eef34ebfc8c'
  first_superuser: 'admin@untimed.com'
  first_superuser_password: 'liveforever1!'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.untimed.com", "https://stag.untimed.com", "https://untimed.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@untimed.com'
  postgres_password: 'liveforever1!'
  pgadmin_default_user: 'admin@untimed.com'
  pgadmin_default_user_password: 'liveforever1!'
  traefik_constraint_tag: 'untimed.com'
  traefik_constraint_tag_staging: 'stag.untimed.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:liveforever1!'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
